### PR TITLE
Configuration: variable zapPath can point to the correct core zap jar file, added skip parameter

### PR DESCRIPTION
**Pull request by msignoriniIon**

### CODE REVIEW

**Comment by msignoriniIon** [comment]
I added also the possibility to skip the plugin execution like a great number of maven plugins.

**Comment by tfcporciuncula** [comment]
I think we could be better with two different PRs, one specific for the _skip_ parameter. The build broke after you committed the changes to add the _skip_ parameter. It seems there is something wrong with the imports in ZapMojo.

https://travis-ci.org/pdsoftplan/zap-maven-plugin/jobs/129780121

**Comment by msignoriniIon** [comment]
Sorry for the build failure.
Can be the pull request be accepted?

**Comment by fabiusks** [comment]
Merged!

Thanks msignoriniIon =)

**Comment by tfcporciuncula** [comment]
This closes #1.

**Pull request merged**
